package com.synapticloop.sample.h2zero.sqlite3.upserter;

//        - - - - thoughtfully generated by synapticloop h2zero - - - -        
//          with the use of synapticloop templar templating language
//               (/java/upserter/java-create-upserter.templar)


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


import com.synapticloop.sample.h2zero.sqlite3.model.util.Constants;

public class AllTypesUpserter {
	// the binder is unused in code, but will generate compile problems if this 
	// class is no longer referenced in the h2zero file. Just a nicety for
	// removing dead code
	@SuppressWarnings("unused")
	private static final String BINDER = Constants.ALL_TYPES_BINDER;

	private static final Logger LOGGER = LoggerFactory.getLogger(AllTypesUpserter.class);
	private static final String SQL_SELECT_START = 
		"""
			select 
				id_all_types, 
				test_bigint, 
				test_boolean, 
				test_date, 
				test_datetime, 
				test_double, 
				test_float, 
				test_int, 
				test_integer, 
				test_mediumint, 
				test_numeric, 
				test_smallint, 
				test_text, 
				test_tinyint, 
				test_varchar
			from 
				all_types
		""";
	private static final String SQL_BUILTIN_FIND_BY_PRIMARY_KEY = SQL_SELECT_START + " where id_all_types = ?";

	/**
	 * <p>This SQL statement was generated from the <code>findByIdAllTypes</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_ID_ALL_TYPES = SQL_SELECT_START + 
		"""
			where id_all_types = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestBigint</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_BIGINT = SQL_SELECT_START + 
		"""
			where test_bigint = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestBoolean</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_BOOLEAN = SQL_SELECT_START + 
		"""
			where test_boolean = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestDate</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_DATE = SQL_SELECT_START + 
		"""
			where test_date = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestDatetime</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_DATETIME = SQL_SELECT_START + 
		"""
			where test_datetime = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestDouble</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_DOUBLE = SQL_SELECT_START + 
		"""
			where test_double = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestFloat</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_FLOAT = SQL_SELECT_START + 
		"""
			where test_float = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestInt</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_INT = SQL_SELECT_START + 
		"""
			where test_int = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestInteger</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_INTEGER = SQL_SELECT_START + 
		"""
			where test_integer = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestMediumint</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_MEDIUMINT = SQL_SELECT_START + 
		"""
			where test_mediumint = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestNumeric</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_NUMERIC = SQL_SELECT_START + 
		"""
			where test_numeric = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestSmallint</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_SMALLINT = SQL_SELECT_START + 
		"""
			where test_smallint = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestText</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_TEXT = SQL_SELECT_START + 
		"""
			where test_text = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestTinyint</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_TINYINT = SQL_SELECT_START + 
		"""
			where test_tinyint = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByTestVarchar</code> definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_TEST_VARCHAR = SQL_SELECT_START + 
		"""
			where test_varchar = ?
		""";

	private AllTypesUpserter() {}

}