package com.synapticloop.sample.h2zero.sqlite3.test.util;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//          (tests/java-sqlite3-database-test-base.templar)


import static org.junit.Assert.*;

import com.synapticloop.h2zero.base.manager.BaseConnectionManager;import com.synapticloop.sample.h2zero.sqlite3.ConnectionManagerInitialiserOverride;
import com.synapticloop.h2zero.base.manager.sqlite3.ConnectionManager;
import com.mchange.v2.c3p0.ComboPooledDataSource;
import org.junit.AfterClass;
import org.junit.BeforeClass;

public class DatabaseSetupTest extends BaseConnectionManager {
	private static final String DB_DRIVER_CLASS = "org.sqlite.JDBC";

	@BeforeClass
	public static void beforeClass() {
		ConnectionManagerInitialiserOverride.initialise();
	}

	@AfterClass
	public static void teardown() {
		// ConnectionManagerInitialiserOverride.destroy();
	}
}
