package synapticloop.workitemiser.database.mysql.h2zero.finder;

//        - - - - thoughtfully generated by synapticloop h2zero - - - -        
//          with the use of synapticloop templar templating language
//                  (/java/finder/java-create-finder.templar)

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Date;
import java.math.BigDecimal;
import java.util.List;
import java.util.ArrayList;

import com.synapticloop.h2zero.base.exception.H2ZeroFinderException;
import com.synapticloop.h2zero.base.manager.mysql.ConnectionManager;
import com.synapticloop.h2zero.base.util.LruCache;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


import synapticloop.workitemiser.database.mysql.h2zero.model.util.Constants;

import synapticloop.workitemiser.database.mysql.h2zero.model.AgencyAgreement;

import com.synapticloop.h2zero.base.sql.limitoffset.MultiFinder;
import com.synapticloop.h2zero.base.sql.limitoffset.UniqueFinder;

/**
 * <p>This is the finders for the <code>agency_agreement</code> table or view.</p>
 * 
 * <p>It contains all defined finders for this table.</p>
 * 
 * <p>In-built finders:</p>
 * 
 * <ul>
 *   <li><code>findByPrimaryKey</code>: this will always return the
 *     <code>AgencyAgreement</code> object, or null if the object
 *     cannot be found</li>
 *   <li><code>findAll</code>: this will always return a 
 *     <code>List&lt;AgencyAgreement&gt;</code> of objects, or an empty
 *     list.  This finder can also use limits and offsets.</li>
 * </ul>
 * 
 * <p>There are 8 user defined finders:
 *
 * <ul>
 *   <li><code>findByNumStrataPlan</code> - Generated from the 'fieldFinders' JSON key</li>
 *   <li><code>findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAsc</code> - Generated from the 'fieldFinders' JSON key</li>
 *   <li><code>findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAscFlIsCurrentDesc</code> - Generated from the 'fieldFinders' JSON key</li>
 *   <li><code>findByNumStrataPlanNotNullFlIsCurrentNullOrderedByNumStrataPlanAscFlIsCurrentDesc</code> - Generated from the 'fieldFinders' JSON key</li>
 *   <li><code>findByNullTxtNotes</code> - Generated from the 'fieldFinders' JSON key</li>
 *   <li><code>findByNotNullTxtNotes</code> - Generated from the 'fieldFinders' JSON key</li>
 *   <li><code>findAllOrdered</code> - Generated from the 'finders' JSON key</li>
 *   <li><code>findRolloversByMonth</code> - Generated from the 'finders' JSON key</li>
 * <ul>
 * 
 * @author synapticloop h2zero generator
 */

public class AgencyAgreementFinder {
	// the binder is unused in code, but will generate compile problems if this 
	// class is no longer referenced in the h2zero file. Just a nicety for
	// removing dead code
	@SuppressWarnings("unused")
	private static final String BINDER = Constants.AGENCY_AGREEMENT_BINDER;

	/**
	 * <p>The default logger implementation</p>
	 */
	private static final Logger LOGGER = LoggerFactory.getLogger(AgencyAgreementFinder.class);
	/**
	 * <p>This is the start of all SQL select queries</p>
	 */
	private static final String SQL_SELECT_START = 
		"""
			select 
				id_agency_agreement, 
				num_strata_plan, 
				dt_agency_agreement_start, 
				dt_agency_agreement_end, 
				flt_percent_increase, 
				txt_notes, 
				fl_is_current
			from 
				agency_agreement
		""";
	private static final String SQL_BUILTIN_FIND_BY_PRIMARY_KEY = SQL_SELECT_START + " where id_agency_agreement = ?";

	/**
	 * <p>This SQL statement was generated from the <code>findByNumStrataPlan</code>
	 * definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_NUM_STRATA_PLAN = SQL_SELECT_START + 
		"""
			where num_strata_plan = ?
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAsc</code>
	 * definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_NUM_STRATA_PLAN_FL_IS_CURRENT_ORDERED_BY_NUM_STRATA_PLAN_ASC = SQL_SELECT_START + 
		"""
			where num_strata_plan = ? and fl_is_current = ?
		""" + " order by num_strata_plan asc";
	/**
	 * <p>This SQL statement was generated from the <code>findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAscFlIsCurrentDesc</code>
	 * definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_NUM_STRATA_PLAN_FL_IS_CURRENT_ORDERED_BY_NUM_STRATA_PLAN_ASC_FL_IS_CURRENT_DESC = SQL_SELECT_START + 
		"""
			where num_strata_plan = ? and fl_is_current = ?
		""" + " order by num_strata_plan asc, fl_is_current desc";
	/**
	 * <p>This SQL statement was generated from the <code>findByNumStrataPlanNotNullFlIsCurrentNullOrderedByNumStrataPlanAscFlIsCurrentDesc</code>
	 * definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_NUM_STRATA_PLAN_NOT_NULL_FL_IS_CURRENT_NULL_ORDERED_BY_NUM_STRATA_PLAN_ASC_FL_IS_CURRENT_DESC = SQL_SELECT_START + 
		"""
			where num_strata_plan is  not  null  and fl_is_current is  null 
		""" + " order by num_strata_plan asc, fl_is_current desc";
	/**
	 * <p>This SQL statement was generated from the <code>findByNullTxtNotes</code>
	 * definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_NULL_TXT_NOTES = SQL_SELECT_START + 
		"""
			where txt_notes is null
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findByNotNullTxtNotes</code>
	 * definition for <code>fieldFinders</code> JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_BY_NOT_NULL_TXT_NOTES = SQL_SELECT_START + 
		"""
			where txt_notes is not null
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findAllOrdered</code> definition for <code>finders</code>
	 * JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_ALL_ORDERED = SQL_SELECT_START + 
		"""
			where 1=1
			order by num_strata_plan asc, dt_agency_agreement desc
		""";
	/**
	 * <p>This SQL statement was generated from the <code>findRolloversByMonth</code> definition for <code>finders</code>
	 * JSON key in the h2zero file.</p>
	 */
	private static final String SQL_FIND_ROLLOVERS_BY_MONTH = SQL_SELECT_START + 
		"""
			where
			month(current()) = month(?)
			order by num_strata_plan asc
		""";
	/**
	 * <p>Private constructor to 'deter' instantiation :)</p>
	 */
	private AgencyAgreementFinder() {}

	/**
	 * <p>Create a Finder that can find a unique row of the <code>agency_agreement</code> table or view by its primary key.</p>
	 * 
	 * <p>This will return a <code>UniqueFinder</code> instance.  To execute the finder, either call:</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown, or</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed, and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByPrimaryKey(primaryKey)
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByPrimaryKey(primaryKey)
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>All the above methods will either:</p>

	 * 
	 * <ul>
	 *   <li>Return a <code>AgencyAgreement</code> object, or</li>
	 *   <li>Return <code>null</code> if the row could not be found, or</li>
	 *   <li>Throw an exception if there was an error executing the query (if not executed silently).</li>
	 * </ul>
	 * 
	 * <p>See {@link #SQL_BUILTIN_FIND_BY_PRIMARY_KEY the SQL statement that is executed} (<code>SQL_BUILTIN_FIND_BY_PRIMARY_KEY</code>)</p>
	 * 
	 * @param idAgencyAgreement the primary key
	 * 
	 * @return the parameterised <code>UniqueFinder</code>
	 */
	public static UniqueFinder<AgencyAgreement> findByPrimaryKey(Long idAgencyAgreement) {
		return(new UniqueFinder<>(
				LOGGER,
				SQL_BUILTIN_FIND_BY_PRIMARY_KEY,
				resultSet -> { try { return list(resultSet); } catch (SQLException e) { return(null); }},
				idAgencyAgreement
		));
	}

	/**
	 * <p>Create a MultiFinder that can find all AgencyAgreement rows</p>
	 * <p>
	 * <p>This will return a UniqueFinder, to execute the finder, either call</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findAll()
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findAll()
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>Additionally, you can limit and offset this query (with or without a connection)</p>
	 * 
	 * <pre>AgencyAgreementFinder.findAll()
	 *     .withLimit(limit)
	 *     .withOffset(offset)
	 *     .executeSilent();</pre>
	 * 
	 * @return the parameterised MultiFinder
	 */
	public static MultiFinder<AgencyAgreement> findAll() {
		return(
				new MultiFinder<AgencyAgreement>(
				LOGGER,
				SQL_SELECT_START,
				resultSet -> { try {return list(resultSet);} catch (SQLException e) { return(null); }},
				new Object[] {}
		));
	}


	/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	 * 
	 * This is the start of the user defined finders which are generated
	 * through either the "finders" JSON key, or the "fieldFinders" JSON
	 * key.
	 * 
	 * There are 8 defined finders on the agency_agreement table, of those finders
	 * the following are the regular finders, either defined through the
	 * 'finders' or 'fieldFinders' JSON key
	 * 
	 * - findByNumStrataPlan - Generated from the 'fieldFinders' JSON key
	 * - findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAsc - Generated from the 'fieldFinders' JSON key
	 * - findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAscFlIsCurrentDesc - Generated from the 'fieldFinders' JSON key
	 * - findByNumStrataPlanNotNullFlIsCurrentNullOrderedByNumStrataPlanAscFlIsCurrentDesc - Generated from the 'fieldFinders' JSON key
	 * - findByNullTxtNotes - Generated from the 'fieldFinders' JSON key
	 * - findByNotNullTxtNotes - Generated from the 'fieldFinders' JSON key
	 * - findAllOrdered - Generated from the 'finders' JSON key
	 * - findRolloversByMonth - Generated from the 'finders' JSON key
	 * 
	 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */


	/**
	 * <p>This is the <code>findByNumStrataPlan</code> finder for the <code>AGENCY_AGREEMENT table.</code></p>
	 * 
	 * <p><em>(This finder was generated through the '<code>fieldFinders</code>' JSON key)</em></p>
	 * 
	 * <p>Create a MultiFinder<AgencyAgreement> Finder that can be invoked through:</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlan(...)
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlan(...)
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>Additionally, you can limit and offset this query (with or without a connection)</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlan(...)
	 *     .withLimit(limit)
	 *     .withOffset(offset)
	 *     .executeSilent();</pre>
	 * 
	 * <p>See {@link #SQL_FIND_BY_NUM_STRATA_PLAN the SQL statement that is executed} (<code>SQL_FIND_BY_NUM_STRATA_PLAN</code>)</p>
	 * 
	 * @param numStrataPlan - maps to the <code>AGENCY_AGREEMENT.num_strata_plan</code> field
	 * 
	 * @return the parameterised MultiFinder()
	 * 
	 */
	public static MultiFinder<AgencyAgreement> findByNumStrataPlan(Integer numStrataPlan) {
		return(
				new MultiFinder<AgencyAgreement>(
				LOGGER,
				SQL_FIND_BY_NUM_STRATA_PLAN,
				resultSet -> { try {return list(resultSet);} catch (SQLException e) { return(null); }},
				new Object[] {numStrataPlan}
		));
	}

	/**
	 * <p>This is the <code>findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAsc</code> finder for the <code>AGENCY_AGREEMENT table.</code></p>
	 * 
	 * <p><em>(This finder was generated through the '<code>fieldFinders</code>' JSON key)</em></p>
	 * 
	 * <p>Create a MultiFinder<AgencyAgreement> Finder that can be invoked through:</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAsc(...)
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAsc(...)
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>Additionally, you can limit and offset this query (with or without a connection)</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAsc(...)
	 *     .withLimit(limit)
	 *     .withOffset(offset)
	 *     .executeSilent();</pre>
	 * 
	 * <p>See {@link #SQL_FIND_BY_NUM_STRATA_PLAN_FL_IS_CURRENT_ORDERED_BY_NUM_STRATA_PLAN_ASC the SQL statement that is executed} (<code>SQL_FIND_BY_NUM_STRATA_PLAN_FL_IS_CURRENT_ORDERED_BY_NUM_STRATA_PLAN_ASC</code>)</p>
	 * 
	 * @param numStrataPlan - maps to the <code>AGENCY_AGREEMENT.num_strata_plan</code> field
	 * @param flIsCurrent - maps to the <code>AGENCY_AGREEMENT.fl_is_current</code> field
	 * 
	 * @return the parameterised MultiFinder()
	 * 
	 */
	public static MultiFinder<AgencyAgreement> findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAsc(Integer numStrataPlan, Boolean flIsCurrent) {
		return(
				new MultiFinder<AgencyAgreement>(
				LOGGER,
				SQL_FIND_BY_NUM_STRATA_PLAN_FL_IS_CURRENT_ORDERED_BY_NUM_STRATA_PLAN_ASC,
				resultSet -> { try {return list(resultSet);} catch (SQLException e) { return(null); }},
				new Object[] {numStrataPlan, flIsCurrent}
		));
	}

	/**
	 * <p>This is the <code>findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAscFlIsCurrentDesc</code> finder for the <code>AGENCY_AGREEMENT table.</code></p>
	 * 
	 * <p><em>(This finder was generated through the '<code>fieldFinders</code>' JSON key)</em></p>
	 * 
	 * <p>Create a MultiFinder<AgencyAgreement> Finder that can be invoked through:</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAscFlIsCurrentDesc(...)
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAscFlIsCurrentDesc(...)
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>Additionally, you can limit and offset this query (with or without a connection)</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAscFlIsCurrentDesc(...)
	 *     .withLimit(limit)
	 *     .withOffset(offset)
	 *     .executeSilent();</pre>
	 * 
	 * <p>See {@link #SQL_FIND_BY_NUM_STRATA_PLAN_FL_IS_CURRENT_ORDERED_BY_NUM_STRATA_PLAN_ASC_FL_IS_CURRENT_DESC the SQL statement that is executed} (<code>SQL_FIND_BY_NUM_STRATA_PLAN_FL_IS_CURRENT_ORDERED_BY_NUM_STRATA_PLAN_ASC_FL_IS_CURRENT_DESC</code>)</p>
	 * 
	 * @param numStrataPlan - maps to the <code>AGENCY_AGREEMENT.num_strata_plan</code> field
	 * @param flIsCurrent - maps to the <code>AGENCY_AGREEMENT.fl_is_current</code> field
	 * 
	 * @return the parameterised MultiFinder()
	 * 
	 */
	public static MultiFinder<AgencyAgreement> findByNumStrataPlanFlIsCurrentOrderedByNumStrataPlanAscFlIsCurrentDesc(Integer numStrataPlan, Boolean flIsCurrent) {
		return(
				new MultiFinder<AgencyAgreement>(
				LOGGER,
				SQL_FIND_BY_NUM_STRATA_PLAN_FL_IS_CURRENT_ORDERED_BY_NUM_STRATA_PLAN_ASC_FL_IS_CURRENT_DESC,
				resultSet -> { try {return list(resultSet);} catch (SQLException e) { return(null); }},
				new Object[] {numStrataPlan, flIsCurrent}
		));
	}

	/**
	 * <p>This is the <code>findByNumStrataPlanNotNullFlIsCurrentNullOrderedByNumStrataPlanAscFlIsCurrentDesc</code> finder for the <code>AGENCY_AGREEMENT table.</code></p>
	 * 
	 * <p><em>(This finder was generated through the '<code>fieldFinders</code>' JSON key)</em></p>
	 * 
	 * <p>Create a MultiFinder<AgencyAgreement> Finder that can be invoked through:</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlanNotNullFlIsCurrentNullOrderedByNumStrataPlanAscFlIsCurrentDesc(...)
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlanNotNullFlIsCurrentNullOrderedByNumStrataPlanAscFlIsCurrentDesc(...)
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>Additionally, you can limit and offset this query (with or without a connection)</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNumStrataPlanNotNullFlIsCurrentNullOrderedByNumStrataPlanAscFlIsCurrentDesc(...)
	 *     .withLimit(limit)
	 *     .withOffset(offset)
	 *     .executeSilent();</pre>
	 * 
	 * <p>See {@link #SQL_FIND_BY_NUM_STRATA_PLAN_NOT_NULL_FL_IS_CURRENT_NULL_ORDERED_BY_NUM_STRATA_PLAN_ASC_FL_IS_CURRENT_DESC the SQL statement that is executed} (<code>SQL_FIND_BY_NUM_STRATA_PLAN_NOT_NULL_FL_IS_CURRENT_NULL_ORDERED_BY_NUM_STRATA_PLAN_ASC_FL_IS_CURRENT_DESC</code>)</p>
	 * 
	 * 
	 * @return the parameterised MultiFinder()
	 * 
	 */
	public static MultiFinder<AgencyAgreement> findByNumStrataPlanNotNullFlIsCurrentNullOrderedByNumStrataPlanAscFlIsCurrentDesc() {
		return(
				new MultiFinder<AgencyAgreement>(
				LOGGER,
				SQL_FIND_BY_NUM_STRATA_PLAN_NOT_NULL_FL_IS_CURRENT_NULL_ORDERED_BY_NUM_STRATA_PLAN_ASC_FL_IS_CURRENT_DESC,
				resultSet -> { try {return list(resultSet);} catch (SQLException e) { return(null); }},
				new Object[] {}
		));
	}

	/**
	 * <p>This is the <code>findByNullTxtNotes</code> finder for the <code>AGENCY_AGREEMENT table.</code></p>
	 * 
	 * <p><em>(This finder was generated through the '<code>fieldFinders</code>' JSON key)</em></p>
	 * 
	 * <p>Create a MultiFinder<AgencyAgreement> Finder that can be invoked through:</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNullTxtNotes(...)
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNullTxtNotes(...)
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>Additionally, you can limit and offset this query (with or without a connection)</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNullTxtNotes(...)
	 *     .withLimit(limit)
	 *     .withOffset(offset)
	 *     .executeSilent();</pre>
	 * 
	 * <p>See {@link #SQL_FIND_BY_NULL_TXT_NOTES the SQL statement that is executed} (<code>SQL_FIND_BY_NULL_TXT_NOTES</code>)</p>
	 * 
	 * 
	 * @return the parameterised MultiFinder()
	 * 
	 */
	public static MultiFinder<AgencyAgreement> findByNullTxtNotes() {
		return(
				new MultiFinder<AgencyAgreement>(
				LOGGER,
				SQL_FIND_BY_NULL_TXT_NOTES,
				resultSet -> { try {return list(resultSet);} catch (SQLException e) { return(null); }},
				new Object[] {}
		));
	}

	/**
	 * <p>This is the <code>findByNotNullTxtNotes</code> finder for the <code>AGENCY_AGREEMENT table.</code></p>
	 * 
	 * <p><em>(This finder was generated through the '<code>fieldFinders</code>' JSON key)</em></p>
	 * 
	 * <p>Create a MultiFinder<AgencyAgreement> Finder that can be invoked through:</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNotNullTxtNotes(...)
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNotNullTxtNotes(...)
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>Additionally, you can limit and offset this query (with or without a connection)</p>
	 * 
	 * <pre>AgencyAgreementFinder.findByNotNullTxtNotes(...)
	 *     .withLimit(limit)
	 *     .withOffset(offset)
	 *     .executeSilent();</pre>
	 * 
	 * <p>See {@link #SQL_FIND_BY_NOT_NULL_TXT_NOTES the SQL statement that is executed} (<code>SQL_FIND_BY_NOT_NULL_TXT_NOTES</code>)</p>
	 * 
	 * 
	 * @return the parameterised MultiFinder()
	 * 
	 */
	public static MultiFinder<AgencyAgreement> findByNotNullTxtNotes() {
		return(
				new MultiFinder<AgencyAgreement>(
				LOGGER,
				SQL_FIND_BY_NOT_NULL_TXT_NOTES,
				resultSet -> { try {return list(resultSet);} catch (SQLException e) { return(null); }},
				new Object[] {}
		));
	}

	/**
	 * <p>This is the <code>findAllOrdered</code> finder for the <code>AGENCY_AGREEMENT table.</code></p>
	 * 
	 * <p><em>(This finder was generated through the '<code>finders</code>' JSON key)</em></p>
	 * 
	 * <p>Create a MultiFinder<AgencyAgreement> Finder that can be invoked through:</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findAllOrdered(...)
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findAllOrdered(...)
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>Additionally, you can limit and offset this query (with or without a connection)</p>
	 * 
	 * <pre>AgencyAgreementFinder.findAllOrdered(...)
	 *     .withLimit(limit)
	 *     .withOffset(offset)
	 *     .executeSilent();</pre>
	 * 
	 * <p>See {@link #SQL_FIND_ALL_ORDERED the SQL statement that is executed} (<code>SQL_FIND_ALL_ORDERED</code>)</p>
	 * 
	 * 
	 * @return the parameterised MultiFinder()
	 * 
	 */
	public static MultiFinder<AgencyAgreement> findAllOrdered() {
		return(
				new MultiFinder<AgencyAgreement>(
				LOGGER,
				SQL_FIND_ALL_ORDERED,
				resultSet -> { try {return list(resultSet);} catch (SQLException e) { return(null); }},
				new Object[] {}
		));
	}

	/**
	 * <p>This is the <code>findRolloversByMonth</code> finder for the <code>AGENCY_AGREEMENT table.</code></p>
	 * 
	 * <p><em>(This finder was generated through the '<code>finders</code>' JSON key)</em></p>
	 * 
	 * <p>Create a MultiFinder<AgencyAgreement> Finder that can be invoked through:</p>
	 * 
	 * <ul>
	 *   <li><code>finder.execute();</code> to execute the finder with exceptions thrown</li>
	 *   <li><code>finder.executeSilent();</code> to execute the finder no exceptions (i.e. they are caught, swallowed and logged)</li>
	 * </ul>
	 * 
	 * <p>You may also want to pass in a connection, in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findRolloversByMonth(...)
	 *     .withConnection(connection)
	 *     .execute();</pre>
	 * 
	 * <p>You may also want to pass in a connection without exceptions being thrown,
	 * in which case use the following:</p>
	 * 
	 * <pre>AgencyAgreementFinder.findRolloversByMonth(...)
	 *     .withConnection(connection)
	 *     .executeSilent();</pre>
	 * 
	 * <p>Additionally, you can limit and offset this query (with or without a connection)</p>
	 * 
	 * <pre>AgencyAgreementFinder.findRolloversByMonth(...)
	 *     .withLimit(limit)
	 *     .withOffset(offset)
	 *     .executeSilent();</pre>
	 * 
	 * <p>See {@link #SQL_FIND_ROLLOVERS_BY_MONTH the SQL statement that is executed} (<code>SQL_FIND_ROLLOVERS_BY_MONTH</code>)</p>
	 * 
	 * @param dtAgencyAgreementStart - maps to the <code>AGENCY_AGREEMENT.dt_agency_agreement_start</code> field
	 * 
	 * @return the parameterised MultiFinder()
	 * 
	 */
	public static MultiFinder<AgencyAgreement> findRolloversByMonth(Date dtAgencyAgreementStart) {
		return(
				new MultiFinder<AgencyAgreement>(
				LOGGER,
				SQL_FIND_ROLLOVERS_BY_MONTH,
				resultSet -> { try {return list(resultSet);} catch (SQLException e) { return(null); }},
				new Object[] {dtAgencyAgreementStart}
		));
	}
	/**
	 * <p>Return the results as a list of AgencyAgreement, this will be empty if
	 * none are found.</p>
	 * 
	 * @param resultSet the results as a list of AgencyAgreement
	 * 
	 * @return the list of results
	 * 
	 * @throws SQLException if there was a problem retrieving the results
	 */
	private static List<AgencyAgreement> list(ResultSet resultSet) throws SQLException {
		List<AgencyAgreement> arrayList = new ArrayList<AgencyAgreement>();
		while(resultSet.next()) {
			arrayList.add(new AgencyAgreement(
					ConnectionManager.getNullableResultLong(resultSet, 1),
					ConnectionManager.getNullableResultInt(resultSet, 2),
					ConnectionManager.getNullableResultDate(resultSet, 3),
					ConnectionManager.getNullableResultDate(resultSet, 4),
					ConnectionManager.getNullableResultFloat(resultSet, 5),
					ConnectionManager.getNullableResultString(resultSet, 6),
					ConnectionManager.getNullableResultBoolean(resultSet, 7)));
		}
		return(arrayList);
	}

	/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	 * 
	 * This is the start of the user defined select clause finders which are 
	 * generated through the "finders" JSON key, with a 'selectClause' 
	 * key on the finder.
	 * 
	 * All selectClause finders return a subset of the data from a row of the 
	 * database table (or tables if there is a join statement) as a generated
	 * bean
	 * 
	 * There are 8 defined finders on the agency_agreement table, of those finders
	 * the following are the select clause finders:
	 * 
	 * 
	 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

}