package synapticloop.workitemiser.database.mysql.h2zero.updater;

//        - - - - thoughtfully generated by synapticloop h2zero - - - -        
//          with the use of synapticloop templar templating language
//                 (/java/updater/java-create-updater.templar)

import synapticloop.workitemiser.database.mysql.h2zero.model.util.Constants;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class AgencyAgreementUpdater {
	// the binder is unused in code, but will generate compile problems if this 
	// class is no longer referenced in the h2zero file. Just a nicety for
	// removing dead code
	@SuppressWarnings("unused")
	private static final String BINDER = Constants.AGENCY_AGREEMENT_BINDER;

	/**
	 * <p>The default logger implementation</p>
	 */
	private static final Logger LOGGER = LoggerFactory.getLogger(AgencyAgreementUpdater.class);

	// static fields generated by synapticloop h2zero
	private static final String SQL_UPDATE_START = "update agency_agreement ";

	// static fields generated from the user input

	private AgencyAgreementUpdater() {}

}