package com.synapticloop.sample.h2zero.sqlite3.test.finder;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//            (java/test/java-finder-test.templar)


import static org.junit.Assert.*;

import org.junit.Assert;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import com.synapticloop.sample.h2zero.sqlite3.ConnectionManagerInitialiserOverride;
import com.synapticloop.h2zero.base.manager.sqlite3.ConnectionManager;
import com.synapticloop.sample.h2zero.sqlite3.test.DatabaseSetupTest;


import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.sql.*;
import java.util.List;


import com.synapticloop.sample.h2zero.sqlite3.finder.AuthorStatusFinder;

/**
 * WARNING NOTE: these tests are designed to test the generated SQL statements
 * __NOT__ whether the database actually returns sane results.
 * 
 * These will also test to ensure that connections are setting closed properly
 * so that there are no resource leakages.
 */

public class AuthorStatusTest extends DatabaseSetupTest {

	@Test
	public void testAuthorStatusFindByPrimaryKey() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		// this shouldn't find anything - and we don't care - only about SQLExceptions
		AuthorStatusFinder.findByPrimaryKey(1L)
				.execute();

		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindByPrimaryKeySilent() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		Assert.assertNull(AuthorStatusFinder.findByPrimaryKey(-831486134981L)
				.executeSilent());

		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindByPrimaryKeyWithConnection() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		try (Connection connection = ConnectionManager.getConnection()) {
			AuthorStatusFinder.findByPrimaryKey(1L)
				.withConnection(connection)
				.execute();

		}
		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindByPrimaryKeyWithConnectionSilent() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertNull(AuthorStatusFinder.findByPrimaryKey(-831486134981L)
				.withConnection(connection)
				.executeSilent());

		}
		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAll() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.execute()
				.size());

		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllLimitOffset() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		Assert.assertEquals(1, AuthorStatusFinder.findAll()
			.withLimit(1)
			.withOffset(0)
			.execute()
			.size());
		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllSilent() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.executeSilent()
				.size());

		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllLimitOffsetSilent() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withLimit(1)
				.withOffset(0)
				.executeSilent()
				.size());

		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllWithConnection() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.execute()
				.size());

		}
		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionSilent() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.executeSilent()
				.size());

		}
		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionLimit() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(1)
				.withOffset(0)
				.execute()
				.size());
		}

		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionLimitSilent() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(1)
				.withOffset(0)
				.executeSilent()
				.size());
		}

		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionOffset() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(null)
				.withOffset(1)
				.execute()
				.size());
			Assert.fail("A SQL Exception should have been thrown as there was an offset without a limit set.");		} catch(SQLException ignored) {
		}		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionOffsetSilent() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		try (Connection connection = ConnectionManager.getConnection()) {
			AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(null)
				.withOffset(0)
				.executeSilent();

		}
		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionLimitOffset() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(1)
				.withOffset(0)
				.execute()
				.size());
		}
		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

	@Test
	public void testAuthorStatusFindAllWithNullConnectionLimitOffset() throws SQLException {
		int numConnections = ConnectionManager.getComboPooledDataSource().getNumConnections();
		int numBusyConnections = ConnectionManager.getComboPooledDataSource().getNumBusyConnections();
		Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withConnection(null)
				.withLimit(1)
				.withOffset(0)
				.execute()
				.size());

		Assert.assertEquals(numConnections, ConnectionManager.getComboPooledDataSource().getNumConnections());
		// need to sleep to ensure that the connection has time to close - hacky... :(
		try { Thread.sleep(1); } catch (InterruptedException e) { /* do nothing */ }
		Assert.assertEquals(numBusyConnections, ConnectionManager.getComboPooledDataSource().getNumBusyConnections());
	}

}
