package com.synapticloop.sample.h2zero.sqlite3.test.finder;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//            (java/test/java-finder-test.templar)


import static org.junit.Assert.*;

import org.junit.Assert;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import com.synapticloop.sample.h2zero.sqlite3.ConnectionManagerInitialiserOverride;
import com.synapticloop.h2zero.base.manager.sqlite3.ConnectionManager;
import com.synapticloop.sample.h2zero.sqlite3.test.DatabaseSetupTest;


import java.math.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.sql.*;
import java.util.List;


import com.synapticloop.sample.h2zero.sqlite3.finder.AuthorStatusFinder;

/**
 * WARNING NOTE: these tests are designed to test the generated SQL statements
 * __NOT__ whether the database actually returns sane results.
 * 
 * These will also test to ensure that connections are setting closed properly
 * so that there are no resource leakages.
 */

public class AuthorStatusTest extends DatabaseSetupTest {

	@Test
	public void testAuthorStatusFindByPrimaryKey() throws SQLException {
		AuthorStatusFinder.findByPrimaryKey(1L)
				.execute();

	}

	@Test
	public void testAuthorStatusFindByPrimaryKeySilent() throws SQLException {
		Assert.assertNull(AuthorStatusFinder.findByPrimaryKey(-831486134981L)
				.executeSilent());

	}

	@Test
	public void testAuthorStatusFindByPrimaryKeyWithConnection() throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			AuthorStatusFinder.findByPrimaryKey(1L)
				.withConnection(connection)
				.execute();
		}
	}

	@Test
	public void testAuthorStatusFindByPrimaryKeyWithConnectionSilent() throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertNull(AuthorStatusFinder.findByPrimaryKey(-831486134981L)
				.withConnection(connection)
				.executeSilent());
		}
	}

	@Test
	public void testAuthorStatusFindAll() throws SQLException {
		Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.execute()
				.size());

	}

	@Test
	public void testAuthorStatusFindAllLimitOffset() throws SQLException {
		Assert.assertEquals(1, AuthorStatusFinder.findAll()
			.withLimit(1)
			.withOffset(0)
			.execute()
			.size());
	}

	@Test
	public void testAuthorStatusFindAllSilent() throws SQLException {
		Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.executeSilent()
				.size());

	}

	@Test
	public void testAuthorStatusFindAllLimitOffsetSilent() throws SQLException {
		Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withLimit(1)
				.withOffset(0)
				.executeSilent()
				.size());
	}

	@Test
	public void testAuthorStatusFindAllWithConnection() throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.execute()
				.size());

		}
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionSilent() throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.executeSilent()
				.size());
		}
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionLimit() throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(1)
				.withOffset(0)
				.execute()
				.size());
		}

	}

	@Test
	public void testAuthorStatusFindAllWithConnectionLimitSilent() throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(1)
				.withOffset(0)
				.executeSilent()
				.size());
		}
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionOffset() throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(4, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(null)
				.withOffset(1)
				.execute()
				.size());
			Assert.fail("A SQL Exception should have been thrown as there was an offset without a limit set.");		} catch(SQLException ignored) {
		}
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionOffsetSilent() throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(null)
				.withOffset(0)
				.executeSilent();
		}
	}

	@Test
	public void testAuthorStatusFindAllWithConnectionLimitOffset() throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withConnection(connection)
				.withLimit(1)
				.withOffset(0)
				.execute()
				.size());
		}
	}

	@Test
	public void testAuthorStatusFindAllWithNullConnectionLimitOffset() throws SQLException {
		Assert.assertEquals(1, AuthorStatusFinder.findAll()
				.withConnection(null)
				.withLimit(1)
				.withOffset(0)
				.execute()
				.size());

	}

}
