package com.synapticloop.book.h2zero.sqlite3.inserter;

// - - - - thoughtfully generated by synapticloop h2zero - - - - 
//    with the use of synapticloop templar templating language
//            (java/java-create-inserter.templar)

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.math.BigDecimal;
import java.sql.Timestamp;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.synapticloop.h2zero.base.manager.sqlite3.ConnectionManager;
import com.synapticloop.book.h2zero.sqlite3.model.util.Constants;

/**
 * This class contains the methods to insert new rows into the: 
 *   <code>book.pet</code>
 * table.  The fields that are available are as follows:
 * 
 * <ul>
 *  <li><code>id_pet</code> (bigint)  <strong>NOT</strong> nullable  (PRIMARY)</li>
 *  <li><code>id_user</code> (bigint)  <strong>NOT</strong> nullable </li>
 *  <li><code>nm_pet</code> (varchar)  <strong>NOT</strong> nullable </li>
 *  <li><code>dt_birthday</code> (datetime)  nullable </li>
 * </ul>
 * 
 * @author synapticloop h2zero
 */

public class PetInserter {
	// the binder is unused in code, but will generate compile problems if this 
	// class is no longer referenced in the h2zero file. Just a nicety for
	// removing dead code
	@SuppressWarnings("unused")
	private static final String BINDER = Constants.PET_BINDER;

		private static final Logger LOGGER = LoggerFactory.getLogger(PetInserter.class);

	// static fields generated by synapticloop h2zero
	private static final String SQL_BUILTIN_INSERT_ALL = "insert into pet(id_pet, id_user, nm_pet, dt_birthday)";
	private static final String SQL_BUILTIN_INSERT_VALUES = SQL_BUILTIN_INSERT_ALL + " values (?, ?, ?, ?)";
	// static inserter SQL generated from the user input

	private PetInserter() {}

	/**
	 * Insert a new Pet into the database utilising the passed in connection.
	 * 
	 * @param connection the connection to use for the database, this __MUST__ be 
	 *   closed by the calling function.
	 * @param idPet  maps to id_pet
	 * @param idUser  maps to id_user
	 * @param nmPet  maps to nm_pet
	 * @param dtBirthday  maps to dt_birthday
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 * 
	 * @throws SQLException if there was an error in the SQL insert statement
	 */
	public static int insert(Connection connection, Long idPet, Long idUser, String nmPet, Timestamp dtBirthday) throws SQLException {
		try (PreparedStatement preparedStatement = connection.prepareStatement(SQL_BUILTIN_INSERT_VALUES)) {
			ConnectionManager.setBigint(preparedStatement, 1, idPet);
			ConnectionManager.setBigint(preparedStatement, 2, idUser);
			ConnectionManager.setVarchar(preparedStatement, 3, nmPet);
			ConnectionManager.setDatetime(preparedStatement, 4, dtBirthday);
			return(preparedStatement.executeUpdate());
		}
	}

	/**
	 * Insert a new Pet into the database utilising the passed in connection 
	 * with only the fields that are allowed to be not null.
	 * 
	 * @param connection the connection to use for the database, this __MUST__ be 
	 *   closed by the calling function.
	 * @param idPet  maps to id_pet
	 * @param idUser  maps to id_user
	 * @param nmPet  maps to nm_pet
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 * 
	 * @throws SQLException if there was an error in the SQL insert statement
	 */
	public static int insert(Connection connection, Long idPet, Long idUser, String nmPet) throws SQLException {
		try (PreparedStatement preparedStatement = connection.prepareStatement(SQL_BUILTIN_INSERT_VALUES)) {
			ConnectionManager.setBigint(preparedStatement, 1, idPet);
			ConnectionManager.setBigint(preparedStatement, 2, idUser);
			ConnectionManager.setVarchar(preparedStatement, 3, nmPet);
			ConnectionManager.setDatetime(preparedStatement, 4, null);
			return(preparedStatement.executeUpdate());
		}
	}

	/**
	 * Insert a new Pet into the database a new connection will be retrieved 
	 * from the pool, used and then closed.
	 * 
	 * @param idPet  maps to id_pet
	 * @param idUser  maps to id_user
	 * @param nmPet  maps to nm_pet
	 * @param dtBirthday  maps to dt_birthday
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 * 
	 * @throws SQLException if there was an error in the SQL insert statement
	 */
	public static int insert(Long idPet, Long idUser, String nmPet, Timestamp dtBirthday) throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			return(insert(connection, idPet, idUser, nmPet, dtBirthday));
		}
	}

	/**
	 * Insert a new Pet into the database a new connection will be retrieved 
	 * from the pool, used and then closed. This is for fields which have a nullable allowed default
	 * 
	 * @param idPet  maps to id_pet
	 * @param idUser  maps to id_user
	 * @param nmPet  maps to nm_pet
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 * 
	 * @throws SQLException if there was an error in the SQL insert statement
	 */
	public static int insert(Long idPet, Long idUser, String nmPet) throws SQLException {
		try (Connection connection = ConnectionManager.getConnection()) {
			return(insert(connection, idPet, idUser, nmPet));
		}
	}

	/**
	 * Silently (i.e. swallow any exceptions) Insert a new Pet into the 
	 * database utilising the passed in connection. If an exception is thrown by the
	 * method, the exception message will be logged as an 'error', if 'trace' logging
	 * is enabled, the stack trace will be printed to the output stream.
	 * 
	 * @param connection the connection to use for the database, this __MUST__ be 
	 *   closed by the calling function.
	 * @param idPet  maps to id_pet
	 * @param idUser  maps to id_user
	 * @param nmPet  maps to nm_pet
	 * @param dtBirthday  maps to dt_birthday
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 */
	public static int insertSilent(Connection connection, Long idPet, Long idUser, String nmPet, Timestamp dtBirthday) {
		try {
			return(insert(connection, idPet, idUser, nmPet, dtBirthday));
		} catch (SQLException sqlex) {
			LOGGER.error("SQLException caught, message was: {}", sqlex.getMessage());
			if(LOGGER.isTraceEnabled()){
				sqlex.printStackTrace();
			}
			return(-1);
		}
	}

	/**
	 * Silently (i.e. swallow any exceptions) Insert a new Pet into the 
	 * database utilising the passed in connection. If an exception is thrown by the
	 * method, the exception message will be logged as an 'error', if 'trace' logging
	 * is enabled, the stack trace will be printed to the output stream.
	 * 
	 * This is only for Non-Nullable fields
	 * 
	 * @param connection the connection to use for the database, this __MUST__ be 
	 *   closed by the calling function.
	 * @param idPet  maps to id_pet
	 * @param idUser  maps to id_user
	 * @param nmPet  maps to nm_pet
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 */
	public static int insertSilent(Connection connection, Long idPet, Long idUser, String nmPet) {
		try {
			return(insert(connection, idPet, idUser, nmPet));
		} catch (SQLException sqlex) {
			LOGGER.error("SQLException caught, message was: {}", sqlex.getMessage());
			if(LOGGER.isTraceEnabled()){
				sqlex.printStackTrace();
			}
			return(-1);
		}
	}

	/**
	 * Silently (i.e. swallow any exceptions) Insert a new Pet into the 
	 * database, creating and closing a connection in the process. If an exception is thrown 
	 * by the method, the exception message will be logged as an 'error', if 'trace' logging
	 * is enabled, the stack trace will be printed to the output stream.
	 * 
	 * @param idPet  maps to id_pet
	 * @param idUser  maps to id_user
	 * @param nmPet  maps to nm_pet
	 * @param dtBirthday  maps to dt_birthday
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 */
	public static int insertSilent(Long idPet, Long idUser, String nmPet, Timestamp dtBirthday) {
		try (Connection connection = ConnectionManager.getConnection()){
			return(insert(connection, idPet, idUser, nmPet, dtBirthday));
		} catch (SQLException sqlex) {
			LOGGER.error("SQLException caught, message was: {}", sqlex.getMessage());
			if(LOGGER.isTraceEnabled()){
				sqlex.printStackTrace();
			}
			return(-1);
		}
	}

	/**
	 * Silently (i.e. swallow any exceptions) Insert a new Pet into the 
	 * database, creating and closing a connection in the process. If an exception is thrown 
	 * by the method, the exception message will be logged as an 'error', if 'trace' logging
	 * is enabled, the stack trace will be printed to the output stream.
	 * 
	 * This is for non-nullable fields only
	 * 
	 * @param idPet  maps to id_pet
	 * @param idUser  maps to id_user
	 * @param nmPet  maps to nm_pet
	 * 
	 * @return the number of rows that were inserted, or -1 if an error occurred
	 */
	public static int insertSilent(Long idPet, Long idUser, String nmPet) {
		try (Connection connection = ConnectionManager.getConnection()) {
			return(insert(connection, idPet, idUser, nmPet));
		} catch (SQLException sqlex) {
			LOGGER.error("SQLException caught, message was: {}", sqlex.getMessage());
			if(LOGGER.isTraceEnabled()){
				sqlex.printStackTrace();
			}
			return(-1);
		}
	}

}