package com.synapticloop.sample.h2zero.mariadb.test.counter;

//        - - - - thoughtfully generated by synapticloop h2zero - - - -        
//          with the use of synapticloop templar templating language
//                     (java/test/java-counter-test.templar)


import com.synapticloop.h2zero.base.manager.mariadb.C3P0ConnectionManager;
import org.junit.Test;
import com.synapticloop.sample.h2zero.mariadb.test.DatabaseSetupTest;


import java.sql.Connection;
import java.sql.SQLException;


import com.synapticloop.sample.h2zero.mariadb.counter.UserTypeCounter;

/**
 * <p><strong>WARNING NOTE:</strong> these tests are designed to test the generated SQL statements
 * <strong>__NOT__<strong> whether the database actually returns sane results.<p>
 */

public class UserTypeTest extends DatabaseSetupTest {

	@Test
	public void testUserTypecountAll() throws SQLException {
		UserTypeCounter.countAll()
				.execute();
	}

	@Test
	public void testUserTypecountAllSilent() {
		UserTypeCounter.countAll()
				.executeSilent();
	}

	@Test
	public void testUserTypecountAllWithConnection() throws SQLException {
		try (Connection connection = C3P0ConnectionManager.getConnection()) {
			UserTypeCounter.countAll()
					.withConnection(connection)
					.execute();
		}
	}

	@Test
	public void testUserTypecountAllWithConnectionSilent() throws SQLException {
		try (Connection connection = C3P0ConnectionManager.getConnection()) {
			UserTypeCounter.countAll()
					.withConnection(connection)
					.executeSilent();
		}
	}

	@Test
	public void testUserTypecountAllWithNullConnection() throws SQLException {
		UserTypeCounter.countAll()
				.withConnection(null)
				.execute();
	}

	@Test
	public void testUserTypecountAllWithNullConnectionSilent() {
		UserTypeCounter.countAll()
				.withConnection(null)
				.executeSilent();
	}

}
