package synapticloop.workitemiser.database.mysql.h2zero.model.util;

//        - - - - thoughtfully generated by synapticloop h2zero - - - -        
//          with the use of synapticloop templar templating language
//               (/java/constants/java-create-constants.templar)

/**
 * <p>The Constants class serves a dual purpose to show up compilation errors,
 * and as a resource for code to reference particular table and field values.</p>
 */
public class Constants {
	// The binder variables below are used to show up compilation errors where
	// it has been removed from the generation.

	// Model Binder for the agency_agreement table
	public static final String AGENCY_AGREEMENT_BINDER = "AGENCY_AGREEMENT";

	// Field constants for the agency_agreement table
	public static final String AGENCY_AGREEMENT_ID_AGENCY_AGREEMENT = "idAgencyAgreement";
	public static final String AGENCY_AGREEMENT_NUM_STRATA_PLAN = "numStrataPlan";
	public static final String AGENCY_AGREEMENT_DT_AGENCY_AGREEMENT_START = "dtAgencyAgreementStart";
	public static final String AGENCY_AGREEMENT_DT_AGENCY_AGREEMENT_END = "dtAgencyAgreementEnd";
	public static final String AGENCY_AGREEMENT_FLT_PERCENT_INCREASE = "fltPercentIncrease";
	public static final String AGENCY_AGREEMENT_FL_IS_CURRENT = "flIsCurrent";



}